version: '3.8'
services:
  adminer:
    # container_name: adminer
    image: adminer:${ADMINER_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 8080
      - 9000
    # environment:
    #   ADMINER_PLUGINS: tables-filter tinymce
    #   ADMINER_DESIGN: nette
    #   ADMINER_DEFAULT_SERVER: localhost
