version: '3.5'
services:
  cnpmjs:
    # container_name: cnpmjs
    image: xiewulong/cnpmjs:${CNPMJS_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 7001
      - 7002
    environment:
      DATABASE_DIALECT: mysql
      DATABASE_POOL_MAX_CONNECTIONS: 10
      DATABASE_POOL_MIN_CONNECTIONS: 10
      DATABASE_POOL_MAX_IDLE_TIME: 30000
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD:
      DATABASE_DB: cnpmjs
    volumes:
      - ./cnpmjs/cnpmjs.conf.js:/app/config/cnpmjs.conf.js
      - ./cnpmjs/data:/app/data
