version: '3.8'
services:
  confluence:
    # container_name: confluence
    image: atlassian/confluence:${CONFLUENCE_IMAGE_TAG:-8}
    # image: atlassian/confluence:${CONFLUENCE_IMAGE_TAG:-9}
    restart: unless-stopped
    ports:
      - 8090
      - 8091
    environment:
      ATL_DB_TYPE: mssql/mysql/oracle12c/oracle/postgresql
      ATL_JDBC_URL:
      ATL_JDBC_USER:
      ATL_JDBC_PASSWORD:
      # ATL_PROXY_NAME: confluence.example.com
      # ATL_PROXY_PORT: 443
      # ATL_TOMCAT_SCHEME: https
      # ATL_TOMCAT_SECURE: true
      # JVM_MAXIMUM_MEMORY: 2048m
      JVM_SUPPORT_RECOMMENDED_ARGS: -javaagent:/opt/atlassian/agent.jar
      TZ: Asia/Shanghai
    volumes:
      - ./confluence/atlassian-agent.jar:/opt/atlassian/agent.jar:ro
      - ./confluence/data:/var/atlassian/application-data/confluence
