version: '3.8'
services:
  metabase:
    # container_name: datart
    image: datart/datart:${DATART_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 8080
    # environment:
    volumes:
      - ./datart/datart.conf:/datart/config/datart.conf
      - ./datart/files:/datart/files
