version: '3.8'
services:
  elasticsearch:
    # container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_IMAGE_TAG:-8.12.2}
    # image: elasticsearch:${ELASTICSEARCH_IMAGE_TAG:-8.12.2}
    restart: unless-stopped
    ports:
      - 9200
      - 9300
    environment:
      ES_SETTING_DISCOVERY_TYPE: single-node
      ES_SETTING_XPACK_SECURITY_ENABLED: false
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
