filebeat:
  container_name: filebeat
  image: docker.elastic.co/beats/filebeat:6.3.1
  restart: unless-stopped
  volumes:
    - ./filebeat/data:/usr/share/filebeat/data # 777
    - ./filebeat/filebeat.conf.yml:/usr/share/filebeat/filebeat.yml # 644
    - ./filebeat/logs:/usr/share/filebeat/logs # 777
---
apiVersion: v1
kind: Pod
metadata:
  name: filebeat
  labels:
    type: filebeat
spec:
  containers:
    - name: filebeat
      image: docker.elastic.co/beats/filebeat:6.3.1
      # imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml # 644
        - name: data
          mountPath: /usr/share/filebeat/data # 777
        - name: log
          mountPath: /usr/share/filebeat/log
        - name: logs
          mountPath: /usr/share/filebeat/logs # 777
  volumes:
    - name: config
      hostPath:
        path: ./filebeat/logs
    - name: data
      hostPath:
        path: ./filebeat/data
    - name: log
      persistentVolumeClaim:
        claimName: filebeat-pvc
    - name: logs
      hostPath:
        path: ./filebeat/logs
  # restartPolicy: Always
