version: '3'
services:
  jobmanager:
    image: flink:${FLINK_IMAGE_TAG_NAME:-latest}
    restart: unless-stopped
    expose:
      - 6123
    ports:
      - 8081
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: flink:${FLINK_IMAGE_TAG_NAME:-latest}
    restart: unless-stopped
    expose:
      - 6121
      - 6122
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
