version: '3.6'
services:
  gitlab:
    # container_name: gitlab
    image: gitlab/gitlab-ee:${GITLAB_IMAGE_TAG_NAME:-latest}
    restart: unless-stopped
    ports:
      - 22
      - 80
      - 443
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        roles ['application_role', 'pages_role', 'sidekiq_role']
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
