version: '3.8'
services:
  jira:
    # container_name: jira
    image: atlassian/jira-software:${JIRA_IMAGE_TAG:-9}
    restart: unless-stopped
    ports:
      - 8080
    environment:
      ATL_DB_TYPE: mssql/mysql/mysql57/mysql8/oracle10g/postgres72
      ATL_JDBC_URL:
      ATL_JDBC_USER:
      ATL_JDBC_PASSWORD:
    volumes:
      - ./jira/data:/var/atlassian/application-data/jira
