version: '3.8'
services:
  keycloak:
    # container_name: keycloak
    # image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-nightly}
    # image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-latest}
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-22.0}
    restart: unless-stopped
    ports:
      - 8080
    environment:
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
    command: start-dev  # start --optimized
    # volumes:
    #   - ./jira/atlassian-agent.jar:/opt/atlassian/agent.jar
    #   - ./jira/data:/var/atlassian/application-data/jira
