version: '3.8'
services:
  keycloak:
    # container_name: keycloak
    # image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-latest}
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-22.0}
    restart: unless-stopped
    ports:
      - 8080
    environment:
      # KC_PROXY: edge/reencrypt/passthrough
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
    command: start-dev  # start --optimized
