version: '3.8'
services:
  kibana:
    # container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_IMAGE_TAG:-8.12.2}
    # image: kibana:${KIBANA_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    volumes:
      - ./kibana/config:/usr/share/kibana/config
