version: '3.8'
services:
  kibana:
    # container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_IMAGE_TAG:-6.3.1}
    # image: kibana:${KIBANA_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 5601
    command: --plugins /somewhere/else
    environment:
      ELASTICSEARCH_URL: http://some-elasticsearch:9200
      # KIBANA_DEFAULTAPPID:
      # SERVER_NAME:
      # XPACK_MONITORING_ENABLED:
    volumes:
      - ./kibana/config:/usr/share/kibana/config
