kibana:
  container_name: kibana
  image: docker.elastic.co/kibana/kibana:6.3.1
  # image: kibana:latest
  restart: unless-stopped
  ports:
    - 5601
  command: --plugins /somewhere/else
  environment:
    ELASTICSEARCH_URL: http://some-elasticsearch:9200
    # KIBANA_DEFAULTAPPID:
    # SERVER_NAME:
    # XPACK_MONITORING_ENABLED:
  volumes:
    - ./kibana/config:/usr/share/kibana/config

---
apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    type: kibana
spec:
  containers:
    - name: kibana
      image: kibana:latest
      # imagePullPolicy: Always
      ports:
        - containerPort: 5601
      command: --plugins /somewhere/else
      env:
        - name: ELASTICSEARCH_URL
          value: http://some-elasticsearch:9200
        # - name: KIBANA_DEFAULTAPPID
        #   value:
        # - name: SERVER_NAME
        #   value:
        # - name: XPACK_MONITORING_ENABLED
        #   value:
      volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config
  volumes:
    - name: config
      hostPath:
        path: ./kibana/config
  # restartPolicy: Always
