version: '3.5'
services:
  konga:
    # container_name: konga
    image: pantsel/konga:${KONGA_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 1337
    environment:
      DB_ADAPTER: postgres  # 'mongo','postgres','sqlserver' or 'mysql'
      DB_URI: postgres://postgres:postgres@postgres:5432/postgres?current_schema=public
      NODE_ENV: production
      TOKEN_SECRET: Token secret
