mariadb:
  container_name: mariadb
  image: mariadb:latest
  restart: unless-stopped
  ports:
    - 3306
  # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD:
    MYSQL_RANDOM_ROOT_PASSWORD:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
    MYSQL_DATABASE: app
    MYSQL_USER: app_user
    MYSQL_PASSWORD: app_password
  volumes:
    - ./mariadb/conf.d:/etc/mysql/conf.d
    - ./mariadb/data:/var/lib/mysql

---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    type: mariadb
spec:
  containers:
    - name: mariadb
      image: mariadb:latest
      # imagePullPolicy: Always
      ports:
        - containerPort: 3306
      # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_DATABASE
          value: app
        - name: MYSQL_USER
          value: app_user
        - name: MYSQL_PASSWORD
          value: app_password
      volumeMounts:
        - name: config
          mountPath: /etc/mysql/conf.d
        - name: data
          mountPath: /var/lib/mysql
  volumes:
    - name: config
      hostPath:
        path: ./mariadb/conf.d
    - name: data
      hostPath:
        path: ./mariadb/data
  # restartPolicy: Always
