version: '3.8'
services:
  matomo:
    # container_name: matomo
    image: matomo:${MATOMO_IMAGE_TAG:-fpm-alpine}
    restart: unless-stopped
    ports:
      - 9000
    environment:
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: matomo
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
    volumes:
      - ./matomo/html:/var/www/html
