mongo:
  container_name: mongo
  image: mongo:latest
  restart: unless-stopped
  ports:
    - 27017
  # command: --config /etc/mongod.conf
  environment:
    # MONGO_INITDB_DATABASE: test
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: root
  volumes:
    - ./mongo/data:/data/db
    # - ./mongo/mongod.conf:/etc/mongod.conf
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    type: mongo
spec:
  containers:
    - name: mongo
      image: mongo:latest
      # imagePullPolicy: Always
      ports:
        - containerPort: 27017
      # command: --config /etc/mongod.conf
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
      volumeMounts:
        - name: config
          mountPath: /etc/mongod.conf
        - name: data
          mountPath: /data/db
  volumes:
    - name: config
      hostPath:
        path: ./mongo/mongod.conf
    - name: data
      hostPath:
        path: ./mongo/data
  # restartPolicy: Always
