version: '3.5'
services:
  mysql:
    # container_name: mysql
    image: mysql:${MYSQL_IMAGE_TAG_NAME:-latest}
    restart: unless-stopped
    ports:
      - 3306
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
