version: '3.8'
services:
  nextcloud:
    # container_name: nextcloud
    image: nextcloud:${NEXTCLOUD_IMAGE_TAG:-stable}
    restart: unless-stopped
    ports:
      - 80
    environment:
      MYSQL_HOST:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      REDIS_HOST:
      REDIS_HOST_PORT:
      REDIS_HOST_PASSWORD:
    volumes:
      - ./nextcloud/html:/var/www/html
