version: '3.8'
services:
  nextcloud:
    # container_name: nextcloud
    image: nextcloud:${NEXTCLOUD_IMAGE_TAG:-stable}
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ./nextcloud/html:/var/www/html
