version: '3.5'
services:
  nginx:
    # container_name: nginx
    image: nginx:${NGINX_IMAGE_TAG_NAME:-stable-alpine}
    restart: unless-stopped
    ports:
      - 80
      - 443
    # environment:
    #   NGINX_HOST: foobar.com
    #   NGINX_PORT: 80
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      # - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/templates:/etc/nginx/templates:ro
