version: '3.8'
services:
  redis:
    # container_name: redis
    image: redis:${REDIS_IMAGE_TAG:-alpine}
    restart: unless-stopped
    ports:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
