version: '3.5'
services:
  strapi:
    # container_name: strapi
    image: strapi/strapi:${STRAPI_IMAGE_TAG_NAME:-latest}
    restart: unless-stopped
    ports:
      - 1337
    environment:
      DATABASE_CLIENT: sqlite  # sqlite, postgres, mysql ,mongo
      DATABASE_HOST:
      DATABASE_PORT:
      DATABASE_NAME:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
    volumes:
      - ./strapi/app:/srv/app
