version: '3.5'
services:
  xxl-job:
    # container_name: xxl-job
    image: xuxueli/xxl-job-admin:${XXL_JOB_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - 8080
    environment:
      # JAVA_OPTS: "-Xmx512m"
      PARAMS: "--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
    volumes:
      - ./xxl-job/logs:/data/applogs
