#!/bin/bash

app=mariadb
name=`whoami`
dir=$(cd `dirname $0`; pwd)
port=3306
password=root

eval set -- `getopt -q -o n:N:p:P: "$@"`
while true
do
	case $1 in
		-n) name=${name}-$2; shift 2;;
		-N) name=$2; shift 2;;
		-p) port=$2:${port}; shift 2;;
		-P) password=$2; shift 2;;
		--) shift; break;;
	esac
done

alias=${app}-${name}

case $1 in
	start)
		if [ ! `docker start ${alias} 2> /dev/null` ]; then
			docker run --name ${alias} -p ${port} -e MYSQL_PASSWORD=${password} -d xiewulong/mariadb
		fi
		echo "${name}(mariadb) is already running on `docker port ${alias} 3306`."
		;;
	stop) docker stop ${alias};;
	restart) docker restart ${alias};;
	port) docker port ${alias} 3306;;
	*) echo "Usage: $0 {start|stop|restart|port} [-n|N name] [-p ${port}] [-P password]"; exit 1;;
esac
